### ISSUE TITLE
rename columns as statuses

### ISSUE THREAD

**Issue by VasylPosmit** [VasylPosmit/training-2022-09#3]
OBJECTiVE
- set up team workflow (statuses)

ARCH NOTES

- use statuses from the presentation https://docs.google.com/presentation/d/13rt6gzQeSw6QWw9xJo8WgWh77ou3CyecOIEjDbB-ZRA/edit#slide=id.g75bf08179e_0_713

AC
- column naming in GitHub Project are the same as in presentation

**Comment by VasylPosmit** [comment]
There must be no New column

**Comment by TGacek89** [comment]
Fixed
